.TH "main.py" 3 "Tue Nov 29 2022" "Version 1.0" "natural-english-tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmain\&.t\fP = Tokenizer()"
.br
.ti -1c
.RI "string \fBmain\&.text\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for natural-english-tokenizer from the source code\&.
