.TH "md__r_e_a_d_m_e" 3 "Tue Nov 29 2022" "Version 1.0" "natural-english-tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Natural English Tokenizer (NET) 
.PP
NET (Natural English Tokenizer) is a tool that helps in scanning and parsing text written in natural english in order to prepare them for spell-cheking and grammar checking\&.
.SS "Wed Nov 27 18:30 modified the tokenizer as a class"
.IP "\(bu" 2
created scanner module
.IP "\(bu" 2
created tokenizer class in order to allow use of tokenizer objects
.IP "\(bu" 2
created \fBmain\&.py\fP as driver code
.PP
.SS "Wed Nov 19 16:00 initialized the tokenizer repository"
.IP "\(bu" 2
created default \fBstatement\&.py\fP
.IP "\(bu" 2
created readme file
.PP
.PP
### Member of the group 7 G
.IP "\(bu" 2
DIKUBA KINDJEL ALICIA ASHLEY 
.PP

