.TH "statement.py" 3 "Tue Nov 29 2022" "Version 1.0" "natural-english-tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statement.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstatement\&.statement_tokenizer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstatement\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstatement\&.data\fP = statement_tokenizer()"
.br
.ti -1c
.RI "string \fBstatement\&.text\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for natural-english-tokenizer from the source code\&.
