.TH "statement" 3 "Tue Nov 29 2022" "Version 1.0" "natural-english-tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statement
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstatement_tokenizer\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdata\fP = \fBstatement_tokenizer\fP()"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "statement\&.data = \fBstatement_tokenizer\fP()"

.PP
Definition at line \fB59\fP of file \fBstatement\&.py\fP\&.
.SS "string statement\&.text"
\fBInitial value:\fP
.PP
.nf
1 =  """ Living without computers today is close to an impossibility?
2       As our reliance on computers and computer-controlled technologies grows the computer has evolved from a luxury item to a necessity\&."""
.fi
.PP
Definition at line \fB60\fP of file \fBstatement\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for natural-english-tokenizer from the source code\&.
