.TH "scanner/tokenizer.py" 3 "Tue Nov 29 2022" "Version 1.0" "natural-english-tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scanner/tokenizer.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtokenizer\&.Tokenizer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtokenizer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for natural-english-tokenizer from the source code\&.
