.TH "tokenizer.Tokenizer" 3 "Tue Nov 29 2022" "Version 1.0" "natural-english-tokenizer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tokenizer.Tokenizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "list \fBget_statements\fP (self, text)"
.br
.ti -1c
.RI "list \fBget_tokens\fP (self, text)"
.br
.ti -1c
.RI "str \fB__str__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBtokenizer\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def tokenizer\&.Tokenizer\&.__init__ ( self)"

.PP
Definition at line \fB6\fP of file \fBtokenizer\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " str tokenizer\&.Tokenizer\&.__str__ ( self)"

.PP
Definition at line \fB26\fP of file \fBtokenizer\&.py\fP\&.
.SS " list tokenizer\&.Tokenizer\&.get_statements ( self,  text)"

.PP
Definition at line \fB12\fP of file \fBtokenizer\&.py\fP\&.
.SS " list tokenizer\&.Tokenizer\&.get_tokens ( self,  text)"

.PP
Definition at line \fB19\fP of file \fBtokenizer\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for natural-english-tokenizer from the source code\&.
